targets:
  $default:
    builders:
      json_serializable:json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/ui/screen_reference.dart